import assert from "node:assert/strict";
import { test } from "node:test";
import { fileURLToPath } from "node:url";
import { plainRead, sedStreamOnly, segments } from "../src/shell.mjs";

// A plain read skips the decision model, so every doubt must answer "no": each NO below is a command that writes, runs, opens, or touches a credential.
const YES = [
  "ls -la",
  "rg -n foo src | head -5",
  "sed -n 1,80p a.js",
  "sed -n '/start/,/end/p' f",
  "git log --oneline -5",
  "git -C x diff --stat",
  "git log --author=me",
  "git branch -a",
  "git tag --list 'v*'",
  "cat a 2>/dev/null || true",
  "fd -t f . | sed 's|/[^/]*$||' | sort | uniq -c | sort -rn",
  "cat /private/tmp/x.log",
  "gh pr view 3 --comments",
  "gh api repos/o/r/pulls/1/comments --jq '.[].body'",
  "awk '{print $1}' f",
  "echo ---",
  "cd ~/code/x && git status --short",
  "cd '/tmp/a folder'; ls -la",
  'cd "/tmp/a folder" && cat README.md',
  "cd -L ~/code/x && git status --short",
  "cd -P /tmp; ls",
  "cd -LP -L -- ./x && ls",
  "cd -- -folder && ls",
  "cd ~ && pwd",
  'cd "/tmp/[notes]" && ls',
  "cd /tmp/\\[notes\\] && ls",
  "cd '/tmp/a*b' && ls",
  "wc -l < file.txt",
  "rg x 2>&1 | head",
  "find . -name '*.md' -newer package.json",
  "jq '.hooks | keys' settings.json",
  "git status # a plain comment",
  "node bin/jevis.mjs ask --event tool --request 'fix the footer' 'cat > Hero.tsx <<EOF\n<h1 class=\"bg-clip-text\">x</h1>\nEOF'",
  `node "${fileURLToPath(new URL("../bin/jevis.mjs", import.meta.url)).replaceAll("\\", "/")}" lint`,
  "jevis replay abc123 --events tool",
  "node bin/jevis.mjs doctor --offline",
  "jevis mine --since 7d",
  "jevis stats --near",
  "ps aux",
  "ps -Ao pid,comm",
  "ast-grep -p 'console.log($A)' src",
  "ls src/*.ts && wc -l docs/*.md",
  "rg -n 'a*b?[c]' .",
  "rg -n \"\\.mjs files\" README.md --count || true",
  "awk -F: -v OFS=, '{print $1}' f",
  "grep -c \"x\\y\" f",
  "printf '%s %d\\n' hello 42",
  "printf -- '%s\\n' hello",
  "printf '%%n'",
  "printf '%*s' 5 hi",
  "hostname",
  "hostname -sf",
  "hostname -d -i -I -a -A",
  "hostname --short --fqdn --domain --ip-address --all-ip-addresses --alias --all-fqdns",
  "uname -a",
  "uname --kernel-name --machine",
  "date +%F",
  "date -u -d 'yesterday' +%F",
  "date -r 0 +%F",
  "date -v +1d +%F",
  "sysctl -n hw.ncpu",
  "df -h",
  "lsof -nP -i :3000",
  "file --mime-type src/shell.mjs",
  "sort --reverse in",
  "yq '.a' f.yaml",
  "git reflog show --oneline",
  "git config --get --show-origin user.name",
  "git config get user.name",
  "git config list --show-origin",
  "git cat-file -p HEAD",
  "gh run view 1 --json status",
  "stat -f %z file.txt",
  "test -f file.txt",
  "[ -f file.txt ]",
];
const NO = [
  "cat > f <<EOF\nhi\nEOF",
  "echo hi > f",
  "echo hi >> f",
  "ls >| f",
  "cat <>f",
  "tee f",
  "sed -i s/a/b/ f",
  "sed 's/a/b/w out' f",
  "sed 's/a/b/e' f",
  "sed -n '1p;w out' f",
  "sed -f script.sed f",
  "git commit -m x",
  "git branch new",
  "git tag v1",
  "git -c core.pager=sh log",
  "git diff --output=x",
  "git reflog expire --all",
  "git config user.name x",
  "git stash",
  "git remote add o url",
  "rm -rf x",
  "find . -delete",
  "find . -exec rm {} +",
  "fd -x rm",
  "rg --pre sh x",
  "echo $(whoami)",
  "echo `id`",
  'echo "$HOME"',
  "ls $HOME",
  "diff <(ls) <(ls a)",
  "(cd x && ls)",
  "{ ls; }",
  "cat 'unterminated",
  "cat .env.local",
  "printenv",
  "env",
  "cat ~/.aws/credentials",
  "cat id_rsa",
  "cat key.pem",
  "security find-generic-password -w",
  "gh auth token",
  "gh pr view --web",
  "gh api -X POST repos/o/r/issues",
  "gh pr checkout 3",
  "open http://localhost:3000",
  "sort -o out in",
  "uniq a b",
  "awk '{print > \"f\"}' x",
  "awk 'BEGIN{system(\"rm x\")}'",
  "date -s 10:00",
  "cat x | sh",
  "node -e 1",
  "xargs rm",
  "ls; rm x",
  "ls && python3 x.py",
  "curl -s localhost",
  "FOO=1 ls",
  "./ls",
  "/bin/rm x",
  "npm test",
  "node bin/jevis.mjs ask --record 'x'",
  "node /tmp/elsewhere/bin/jevis.mjs ask x",
  "sg wheel -c 'rm -rf x'",
  "awk 'BEGIN{for(k in ENVIRON) print k, ENVIRON[k]}'",
  "cat /proc/self/environ",
  "ps -ef",
  "ps eww",
  "cat ~/.config/gh/hosts.yml",
  "jq . ~/.docker/config.json",
  "cat ~/.zsh_history",
  "rg --hostname-bin=/tmp/x --hyperlink-format=default x",
  "file -C -m magic",
  "tree -R -H . -o x",
  "tree -RH .",
  "yq -s '.a' f.yaml",
  "ast-grep new rule",
  "sysctl -p /etc/sysctl.conf",
  "cat < /dev/tcp/example.com/80",
  "awk --source='BEGIN{system(\"touch x\")}' '{print}' f",
  "awk -e 'BEGIN{print 1}' f",
  "awk -f prog.awk f",
  "git diff --ext-diff",
  "git log -p --textconv",
  "\"g\\it\" status",
  "cat .en?",
  "cat ~/.config/gh/h*sts.yml",
  "cat d*/.e*",
  "wc -l < .e*",
  "cat creds.json",
  "xxd -r - out.bin",
  "uniq - out.txt",
  "gh api --cache 1h repos/o/r",
  "git grep -Ovim foo",
  "git grep -O'sh -c x' foo",
  "ls #; rm -rf x",
  "rg foo # a comment with > in it",
  "node bin/jevis.mjs hook tool",
  "node bin/jevis.mjs trust",
  "jevis export --out x",
  "node other/jevis.mjs ask x",
  "node -e 'require(\"fs\").writeFileSync(\"x\", \"y\")'",
  "printf -v PATH . && git status",
  "printf -vPATH . && git status",
  "printf -vv PATH .",
  "printf -- -v PATH . && git status",
  "printf '%n' PATH && git status",
  "printf '%10n' PATH",
  "printf '%d' 'v=9'",
  "printf '%*s' 'v=9' hi",
  "printf '%d' 'a[1]=9'",
  "cd",
  "cd --help",
  "cd old new && ls",
  "cd -1 && ls",
  "cd +1 && ls",
  "cd -- -1 && ls",
  "cd - && ls",
  "cd ~-1 && ls",
  "cd ~1 && ls",
  "cd -q x && ls",
  "cd -eP x && ls",
  "cd src/* && ls",
  "cd /tmp/[notes] && ls",
  "cd d*/.hidden && ls",
  'cd "$HOME" && ls',
  "cd $(pwd) && ls",
  "cd `pwd` && ls",
  "hostname -F file",
  "hostname -Ffile",
  "hostname --file=x",
  "hostname -b",
  "hostname -sb",
  "hostname newname",
  "hostname --short newname",
  "hostname -- newname",
  "uname -S newname",
  "uname -Snewname",
  "date -a1",
  "date -f +%s +0",
  "date --se=10:00",
  "sysctl --lo=/etc/sysctl.conf",
  "sysctl kernel.hostname=newname",
  "df --sync",
  "df --syn",
  "lsof -D bcache",
  "lsof -Ducache",
  "file -p f",
  "file --preserve-date f",
  "file -z f.gz",
  "file --uncompress-noreport f.gz",
  "file --comp -m magic",
  "sort --out=out in",
  "sort --compress-prog=sh in",
  "sort /O out in",
  "rg -z x",
  "rg --search-zip x",
  "rg --pr=sh x",
  "fd -l .",
  "fd --list-details .",
  "fd --exe=sh .",
  "yq --in-place '.a=1' f.yaml",
  "yq --split-exp-file names f.yaml",
  "yq --inpl '.a=1' f.yaml",
  "ast-grep --update-a -p x -r y",
  "awk '{print}' -f prog.awk f",
  "awk '{print}' -i inplace f",
  "awk '{print}' --source='BEGIN{system(\"touch x\")}' f",
  "git reflog write refs/heads/main old new message",
  "git reflog drop --all",
  "git config --show-origin user.name x",
  "git config --show-origin set user.name x",
  "git config --list --edi",
  "git branch --edit-desc",
  "git branch -vd",
  "git cat-file --filters HEAD:a",
  "git cat-file --filt HEAD:a",
  "git diff --out=out",
  "gh run view 1 --log",
  "gh run view 1 --log-failed",
  "gh api --ca=1h repos/o/r",
  "git tag --list -e",
  "git tag --list -F message",
  "git tag --list --create-reflog",
  "stat -A PATH file.txt && git status",
  "stat -H data file.txt",
  "stat -LAdata file.txt",
  "test -v 'a[v=9]'",
  "[ -v 'a[v=9]' ]",
  "test -R 'a[v=9]'",
  "",
];

test("plainRead: reads pass, and anything that writes, runs, opens, or names a credential does not", () => {
  for (const c of YES.filter((c) => !/^(printf|hostname)\b/.test(c))) assert.equal(plainRead(c), true, `should be a plain read: ${c}`);
  for (const c of NO.filter((c) => !/^(printf|hostname)\b/.test(c))) assert.equal(plainRead(c), false, `should not be a plain read: ${c}`);
});

test("plainRead: printf cannot assign variables or evaluate shell arithmetic", () => {
  for (const c of YES.filter((c) => c.startsWith("printf "))) assert.equal(plainRead(c), true, c);
  for (const c of NO.filter((c) => c.startsWith("printf "))) assert.equal(plainRead(c), false, c);
});

test("plainRead: hostname accepts only documented display forms without operands", () => {
  for (const c of YES.filter((c) => /^hostname\b/.test(c))) assert.equal(plainRead(c), true, c);
  for (const c of NO.filter((c) => /^hostname\b/.test(c))) assert.equal(plainRead(c), false, c);
});

test("sedStreamOnly: prints and stream edits pass; w, e, r, and blocks do not", () => {
  for (const s of ["1,80p", "/a/,/b/p", "$p", "1~2p", "10q", "p ; p", "s|/[^/]*$||", "s/a/b/g;s/c/d/", "s/a\\/b/c/g", "y/ab/cd/"]) assert.equal(sedStreamOnly(s), true, s);
  for (const s of ["s/a/b/w x", "s/a/b/e", "e ls", "r f", "1p;w o", "{p}", "s/a/b"]) assert.equal(sedStreamOnly(s), false, s);
});

test("segments: splits on ; && || | and newlines, keeps quoted operators, and refuses substitution", () => {
  assert.deepEqual(segments("a 'x;y' && b \"p|q\" | c\nd"), [["a", "x;y"], ["b", "p|q"], ["c"], ["d"]]);
  assert.deepEqual(segments("rg x 2>&1 >/dev/null"), [["rg", "x"]]);
  assert.equal(segments("echo $(id)"), null);
  assert.equal(segments("a > out"), null);
});
