import assert from "node:assert/strict";
import { test } from "node:test";
import { plainRead, sedStreamOnly, segments } from "../src/shell.mjs";

// A plain read skips the decision model, so every doubt must answer "no": each NO below is a command that writes, runs, opens, or touches a credential.
const YES = [
  "ls -la",
  "rg -n foo src | head -5",
  "sed -n 1,80p a.js",
  "sed -n '/start/,/end/p' f",
  "git log --oneline -5",
  "git -C x diff --stat",
  "git log --author=me",
  "git branch -a",
  "git tag --list 'v*'",
  "cat a 2>/dev/null || true",
  "fd -t f . | sed 's|/[^/]*$||' | sort | uniq -c | sort -rn",
  "cat /private/tmp/x.log",
  "gh pr view 3 --comments",
  "gh api repos/o/r/pulls/1/comments --jq '.[].body'",
  "awk '{print $1}' f",
  "echo ---",
  "cd ~/code/x && git status --short",
  "wc -l < file.txt",
  "rg x 2>&1 | head",
  "find . -name '*.md' -newer package.json",
  "jq '.hooks | keys' settings.json",
  "git status # a plain comment",
  "node bin/jevis.mjs ask --event tool --request 'fix the footer' 'cat > Hero.tsx <<EOF\n<h1 class=\"bg-clip-text\">x</h1>\nEOF'",
  "node ~/code/jevis/bin/jevis.mjs lint",
  "jevis replay abc123 --events tool",
  "node bin/jevis.mjs doctor --offline",
  "jevis mine --since 7d",
  "jevis stats --near",
  "ps aux",
  "ps -Ao pid,comm",
  "ast-grep -p 'console.log($A)' src",
  "ls src/*.ts && wc -l docs/*.md",
  "rg -n 'a*b?[c]' .",
  "rg -n \"\\.mjs files\" README.md --count || true",
  "awk -F: -v OFS=, '{print $1}' f",
  "grep -c \"x\\y\" f",
];
const NO = [
  "cat > f <<EOF\nhi\nEOF",
  "echo hi > f",
  "echo hi >> f",
  "ls >| f",
  "cat <>f",
  "tee f",
  "sed -i s/a/b/ f",
  "sed 's/a/b/w out' f",
  "sed 's/a/b/e' f",
  "sed -n '1p;w out' f",
  "sed -f script.sed f",
  "git commit -m x",
  "git branch new",
  "git tag v1",
  "git -c core.pager=sh log",
  "git diff --output=x",
  "git reflog expire --all",
  "git config user.name x",
  "git stash",
  "git remote add o url",
  "rm -rf x",
  "find . -delete",
  "find . -exec rm {} +",
  "fd -x rm",
  "rg --pre sh x",
  "echo $(whoami)",
  "echo `id`",
  'echo "$HOME"',
  "ls $HOME",
  "diff <(ls) <(ls a)",
  "(cd x && ls)",
  "{ ls; }",
  "cat 'unterminated",
  "cat .env.local",
  "printenv",
  "env",
  "cat ~/.aws/credentials",
  "cat id_rsa",
  "cat key.pem",
  "security find-generic-password -w",
  "gh auth token",
  "gh pr view --web",
  "gh api -X POST repos/o/r/issues",
  "gh pr checkout 3",
  "open http://localhost:3000",
  "sort -o out in",
  "uniq a b",
  "awk '{print > \"f\"}' x",
  "awk 'BEGIN{system(\"rm x\")}'",
  "date -s 10:00",
  "cat x | sh",
  "node -e 1",
  "xargs rm",
  "ls; rm x",
  "ls && python3 x.py",
  "curl -s localhost",
  "FOO=1 ls",
  "./ls",
  "/bin/rm x",
  "npm test",
  "node bin/jevis.mjs ask --record 'x'",
  "node /tmp/elsewhere/bin/jevis.mjs ask x",
  "sg wheel -c 'rm -rf x'",
  "awk 'BEGIN{for(k in ENVIRON) print k, ENVIRON[k]}'",
  "cat /proc/self/environ",
  "ps -ef",
  "ps eww",
  "cat ~/.config/gh/hosts.yml",
  "jq . ~/.docker/config.json",
  "cat ~/.zsh_history",
  "rg --hostname-bin=/tmp/x --hyperlink-format=default x",
  "file -C -m magic",
  "tree -R -H . -o x",
  "tree -RH .",
  "yq -s '.a' f.yaml",
  "ast-grep new rule",
  "sysctl -p /etc/sysctl.conf",
  "cat < /dev/tcp/example.com/80",
  "awk --source='BEGIN{system(\"touch x\")}' '{print}' f",
  "awk -e 'BEGIN{print 1}' f",
  "awk -f prog.awk f",
  "git diff --ext-diff",
  "git log -p --textconv",
  "\"g\\it\" status",
  "cat .en?",
  "cat ~/.config/gh/h*sts.yml",
  "cat d*/.e*",
  "wc -l < .e*",
  "cat creds.json",
  "xxd -r - out.bin",
  "uniq - out.txt",
  "gh api --cache 1h repos/o/r",
  "git grep -Ovim foo",
  "git grep -O'sh -c x' foo",
  "ls #; rm -rf x",
  "rg foo # a comment with > in it",
  "node bin/jevis.mjs hook tool",
  "node bin/jevis.mjs trust",
  "jevis export --out x",
  "node other/jevis.mjs ask x",
  "node -e 'require(\"fs\").writeFileSync(\"x\", \"y\")'",
  "",
];

test("plainRead: reads pass, and anything that writes, runs, opens, or names a credential does not", () => {
  for (const c of YES) assert.equal(plainRead(c), true, `should be a plain read: ${c}`);
  for (const c of NO) assert.equal(plainRead(c), false, `should not be a plain read: ${c}`);
});

test("sedStreamOnly: prints and stream edits pass; w, e, r, and blocks do not", () => {
  for (const s of ["1,80p", "/a/,/b/p", "$p", "1~2p", "10q", "p ; p", "s|/[^/]*$||", "s/a/b/g;s/c/d/", "s/a\\/b/c/g", "y/ab/cd/"]) assert.equal(sedStreamOnly(s), true, s);
  for (const s of ["s/a/b/w x", "s/a/b/e", "e ls", "r f", "1p;w o", "{p}", "s/a/b"]) assert.equal(sedStreamOnly(s), false, s);
});

test("segments: splits on ; && || | and newlines, keeps quoted operators, and refuses substitution", () => {
  assert.deepEqual(segments("a 'x;y' && b \"p|q\" | c\nd"), [["a", "x;y"], ["b", "p|q"], ["c"], ["d"]]);
  assert.deepEqual(segments("rg x 2>&1 >/dev/null"), [["rg", "x"]]);
  assert.equal(segments("echo $(id)"), null);
  assert.equal(segments("a > out"), null);
});
